/* CONSUTA 3

POR CADA PLATO, CUAL ES SU COSTO DE PRODUCCION Y CUAL ES SU COSTO DE VENTA */

/* ACTULIZAR COSTO DE PREPARACION Y PRECIO DE VENTA */
UPDATE PLATO SET PRECIO =(
SELECT SUM(INGREDIENTE.PRECIO_INGREDIENTE * CANTIDAD_INGREDIENTE)
FROM INGREDIENTE
INNER JOIN DETALLE_PLATO ON INGREDIENTE.ID_INGREDIENTE= DETALLE_PLATO.ID_INGREDIENTE 
WHERE PLATO.ID_PLATO=DETALLE_PLATO.ID_PLATO )
UPDATE PLATO SET PRECIO_VENTA =(PRECIO+2)
/* FIN DE ACTULIZACION*/

/* CONSULTA*/
SELECT 
ID_PLATO AS CODIGO,
NOMBRE_PLATO AS PLATO,
PRECIO AS COSTO_PRODUCCION,
PRECIO_VENTA
FROM PLATO WHERE PRECIO_VENTA >0 ;