/* CONSUTA 2

NÚMERO DE VECES EN EL QUE UN CLIENTE HA RESERVADO Y CUMPLIO, Y EL NÚMERO DE VECES QUE EL CLIENTE RESERVO Y NO CUMPLIO */

SELECT 
(NOMBRE_CLIENTE ||' '|| APELLIDO_CLIENTE) AS NOMBRE,
COUNT(RESERVACION.ESTADO ) as cantidad,'Cumplio' as estado
FROM CLIENTE INNER JOIN RESERVACION ON CLIENTE.ID_CLIENTE =RESERVACION.ID_CLIENTE
WHERE RESERVACION.ESTADO = 'ESTADO001' GROUP BY nombre 
UNION 
SELECT 
(NOMBRE_CLIENTE ||' '|| APELLIDO_CLIENTE) AS NOMBRE,
COUNT(RESERVACION.ESTADO )as cantidad,'no cumplio' 
FROM CLIENTE INNER JOIN RESERVACION ON CLIENTE.ID_CLIENTE =RESERVACION.ID_CLIENTE
WHERE RESERVACION.ESTADO = 'ESTADO003' GROUP BY nombre order by nombre desc;
